# WINDOW_TITLE = "Maze Explorer"

MAZE_WIDTH = 40  ## 40
MAZE_HEIGHT = 20 ## 20
# BLOCK_SIZE = 15

GENERATIONS = 50
# GENERATIONS = 500
POPULATION_SIZE = 100
MUTATION_RATE = 0.1

START_COORDS = (1,1)
END_COORDS = (MAZE_WIDTH-2,MAZE_HEIGHT-2)

